# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

import gui
from params import *


class Ui_MainWindow(object):
    def init_bcg_lbl(self):
        label = QtWidgets.QLabel(self.centralwidget)
        #label.setGeometry(QtCore.QRect(0, 0, 5556, 5574))
        label.setGeometry(0, 0, 600, 750)
        label.setFixedSize(1920, 1080)
        label.setText("")
        label.setPixmap(QtGui.QPixmap("../storage/BackGround/user.jpg"))
        label.setObjectName("bcg_lbl")
        return label

    def init_namelbl(self):
        namelbl = QtWidgets.QLabel(self.centralwidget)
        namelbl.setGeometry(QtCore.QRect(880, 250, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        namelbl.setFont(font)
        namelbl.setStyleSheet("color:white;")
        namelbl.setObjectName("namelbl")
        namelbl.setText("hello Alien")
        return namelbl

    def init_avatarlbl(self):
        avatarlbl = QtWidgets.QLabel(self.centralwidget)
        avatarlbl.setGeometry(QtCore.QRect(850, 60, 180, 180))
        avatarlbl.setStyleSheet("background-color:white;\n"
                                "border-radius:90px;")
        avatarlbl.setObjectName("avatarlbl")
        pixmap = QPixmap(gui.player_global.get_avatar())
        avatarlbl.setPixmap(QPixmap(pixmap))
        avatarlbl.setScaledContents(True)

        return avatarlbl

    def get_back_button(self):
        button = QtWidgets.QPushButton(self.centralwidget)
        button.setGeometry(QtCore.QRect(80, 920, 81, 81))
        button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        button.setStyleSheet(back_button_style)
        button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../storage/Icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        button.setIcon(icon)
        button.setIconSize(QtCore.QSize(80, 80))
        button.setObjectName("back_pushButton")
        return button

    def init_achievements_table(self):
        achievements_table = QtWidgets.QTableWidget(self.centralwidget)
        achievements_table.setGeometry(QtCore.QRect(380, 320, 1150, 300))
        achievements_table.setFixedHeight(570)
        achievements_table.horizontalScrollBar().hide()
        achievements_table.setStyleSheet(achievment_table_style)
        achievements_table.verticalScrollBar().setStyleSheet(scroll_style)


        achievements_table.setObjectName("achievements_table")
        achievements_table.setFont(init_font_start(20, False))
        achievements_table.horizontalHeader().setFont(init_font_start(20, False))
        achievements_table.setColumnCount(2)
        achievements_table.setColumnWidth(0, 622)
        achievements_table.setColumnWidth(1, 526)
        achievements_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        achievements_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)
        achievements_table.verticalHeader().hide()
        achievements_table.setShowGrid(False)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Achievements")
        achievements_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Reward")
        achievements_table.setHorizontalHeaderItem(1, item)
        achievements_table.resetVerticalScrollMode()
        achievements_table.setSortingEnabled(True)
        return achievements_table

    def fill_table(self, list=[]):
        x = [('a', 50), ('b', 10), ('c', 60), ('b', 10), ('c', 60), ('b', 10), ('c', 60)]
        self.achievements_table.setRowCount(len(x))
        j = 0
        for i in x:
            achievment, reward = i
            print(i, j)
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setText(str(achievment))
            self.achievements_table.setItem(j, 0, item)
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setText(str(reward))
            self.achievements_table.setItem(j, 1, item)
            self.achievements_table.setRowHeight(j, 100)
            j += 1

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(gamespace_width, gamespace_height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bcg_lbl = self.init_bcg_lbl()
        self.achievements_table = self.init_achievements_table()
        self.fill_table()
        self.namelbl = self.init_namelbl()
        self.avatarlbl = self.init_avatarlbl()
        self.back_btn = self.get_back_button()
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


# TODO remove and link to profile
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    # app.setStyleSheet(stylesheet)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec_())
